# Generated by Django 2.2.2 on 2021-10-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '后台端用户表', 'verbose_name_plural': '后台端用户表'},
        ),
    ]
