# Generated by Django 2.2.2 on 2021-10-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee', models.CharField(max_length=64, verbose_name='收件人姓名')),
                ('mobile', models.CharField(max_length=16, verbose_name='联系方式')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
                ('transportDay', models.CharField(default='', max_length=64, verbose_name='收货时间')),
                ('is_default', models.BooleanField(default=True, verbose_name='是否为默认地址')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
            },
        ),
        migrations.CreateModel(
            name='good_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='商品分类名称')),
            ],
            options={
                'verbose_name': '主分类',
                'verbose_name_plural': '主分类',
            },
        ),
        migrations.CreateModel(
            name='good_categorychild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='子分类名称')),
                ('img_url', models.CharField(max_length=256, null=True, verbose_name='图片地址')),
                ('category', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applet.good_category', verbose_name='主分类名称')),
            ],
            options={
                'verbose_name': '子分类',
                'verbose_name_plural': '子分类',
            },
        ),
        migrations.CreateModel(
            name='navar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navar_name', models.CharField(max_length=32, verbose_name='名称')),
                ('seq', models.IntegerField(verbose_name='顺序')),
            ],
            options={
                'verbose_name': '首页导航栏',
                'verbose_name_plural': '首页导航栏',
            },
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistics_company', models.SmallIntegerField(choices=[(1, '京东'), (2, '顺丰'), (3, '圆通'), (4, '申通'), (5, '百世')], null=True, verbose_name='物流公司')),
                ('logistics_number', models.CharField(max_length=128, verbose_name='物流订单编号')),
                ('is_free_freight', models.BooleanField(default=True, verbose_name='是否免除运费')),
                ('freight', models.FloatField(default=0, verbose_name='订单运费')),
            ],
            options={
                'verbose_name': '订单详情列表',
                'verbose_name_plural': '订单详情列表',
            },
        ),
        migrations.CreateModel(
            name='productgoods',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('show_img', models.CharField(max_length=256, verbose_name='展示图片路径')),
                ('price', models.FloatField(verbose_name='现价格')),
                ('privilegePrice', models.FloatField(verbose_name='原价格')),
                ('discount', models.FloatField(default=7, verbose_name='折扣')),
                ('show_video', models.CharField(max_length=256, verbose_name='有关视频')),
                ('goods_type', models.SmallIntegerField(choices=[(1, '电脑办公'), (2, '手机'), (3, '运动户外'), (4, '美妆护肤'), (5, '女装')], verbose_name='类型')),
                ('is_putaway', models.BooleanField(default=True, verbose_name='是否上架')),
                ('categorychild', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applet.good_categorychild', verbose_name='所属子分类')),
            ],
            options={
                'verbose_name': '商品列表',
                'verbose_name_plural': '商品列表',
            },
        ),
        migrations.CreateModel(
            name='productgoodsdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('characteristic', models.CharField(max_length=128, verbose_name='规格')),
            ],
            options={
                'verbose_name': '商品详情',
                'verbose_name_plural': '商品详情',
            },
        ),
        migrations.CreateModel(
            name='productsale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('img_url', models.CharField(max_length=128, verbose_name='图片地址')),
                ('type', models.CharField(default='temai', max_length=32, verbose_name='类型')),
                ('remark', models.CharField(max_length=64, verbose_name='描述')),
            ],
            options={
                'verbose_name': '新品特卖',
                'verbose_name_plural': '新品特卖',
            },
        ),
        migrations.CreateModel(
            name='slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=128, verbose_name='名称')),
                ('img_url', models.TextField(verbose_name='图片路径')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('click_url', models.CharField(max_length=256, verbose_name='点击链接')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_openid', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('username', models.CharField(max_length=128, verbose_name='昵称')),
                ('sex', models.IntegerField(help_text='值为1时是男性，为2时是女性，0是未知', verbose_name='性别')),
                ('country', models.CharField(max_length=64, verbose_name='国家')),
                ('province', models.CharField(max_length=64, verbose_name='省份')),
                ('city', models.CharField(max_length=64, verbose_name='城市')),
                ('language', models.CharField(max_length=32, verbose_name='语言')),
                ('headingurl', models.TextField(verbose_name='头像地址')),
                ('user_level', models.SmallIntegerField(choices=[(1, '普通会员'), (2, '白银会员'), (3, '黄金会员'), (4, '砖石会员')], verbose_name='会员等级')),
                ('user_point', models.IntegerField(default=0, verbose_name='积分')),
                ('user_balance', models.FloatField(default=0, verbose_name='余额')),
                ('user_createtime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user_isactive', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '小程序端用户',
                'verbose_name_plural': '小程序端用户',
            },
        ),
        migrations.CreateModel(
            name='productgoodsdetail_slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_slideshow', models.CharField(max_length=256, verbose_name='详情页轮播图')),
                ('productgoods', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='applet.productgoods', verbose_name='关联商品id')),
            ],
            options={
                'verbose_name': '详情页轮播图片',
                'verbose_name_plural': '详情页轮播图片',
            },
        ),
        migrations.CreateModel(
            name='productgoodsdetail_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_img', models.CharField(max_length=256, verbose_name='详情页商品详情图片')),
                ('productgoods', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='applet.productgoods', verbose_name='关联商品id')),
            ],
            options={
                'verbose_name': '详情页详情图片',
                'verbose_name_plural': '详情页详情图片',
            },
        ),
        migrations.AddField(
            model_name='productgoods',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='applet.productgoodsdetail', verbose_name='详情信息'),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, verbose_name='ID')),
                ('order_title', models.CharField(max_length=150, null=True, verbose_name='标题')),
                ('pay_price', models.FloatField(verbose_name='支付金额')),
                ('buy_number', models.IntegerField(default=1, verbose_name='购买数量')),
                ('trade_no', models.CharField(max_length=64, null=True, verbose_name='支付宝流水号')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '已签收'), (5, '待评价'), (6, '已评价')], default=1, verbose_name='订单状态')),
                ('order_createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order_finishtime', models.DateTimeField(null=True, verbose_name='完成时间')),
                ('pay_type', models.CharField(default='支付宝', max_length=16, verbose_name='支付方式')),
                ('order_paytime', models.DateTimeField(null=True, verbose_name='支付时间')),
                ('is_delete', models.BooleanField(default=False, help_text='订单在用户层面是否删除', verbose_name='是否删除')),
                ('order_addr', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='applet.address', verbose_name='关联地址')),
                ('oredr_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applet.order_detail', verbose_name='订单外键')),
                ('productgoods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applet.productgoods', verbose_name='关联商品id')),
                ('user', models.ForeignKey(on_delete=True, to='applet.user', verbose_name='关联用户id')),
            ],
            options={
                'verbose_name': '订单列表',
                'verbose_name_plural': '订单列表',
            },
        ),
        migrations.CreateModel(
            name='goodcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productgood_num', models.CharField(max_length=10, verbose_name='添加到购物车的商品数量')),
                ('goodtocart_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('productgood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goodcart', to='applet.productgoods', verbose_name='关联商品id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applet.user', verbose_name='关联用户id')),
            ],
            options={
                'verbose_name': '用户购物车',
                'verbose_name_plural': '用户购物车',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=True, to='applet.user', verbose_name='关联用户'),
        ),
    ]
