# Generated by Django 2.2.2 on 2021-10-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistics_company', models.CharField(max_length=64, verbose_name='物流公司')),
                ('logistics_number', models.CharField(max_length=128, verbose_name='物流订单编号')),
                ('is_free_freight', models.BooleanField(default=True, verbose_name='是否免除运费')),
                ('freight', models.FloatField(default=0, verbose_name='订单运费')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='logistics_company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='logistics_number',
        ),
        migrations.AddField(
            model_name='order',
            name='buy_number',
            field=models.IntegerField(default=1, verbose_name='购买数量'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(default='支付宝', max_length=16, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='productgoods',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applet.productgoods', verbose_name='关联商品id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '已签收'), (5, '待评价'), (6, '已评价')], verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='goods_type',
            field=models.SmallIntegerField(choices=[(1, '电脑办公'), (2, '手机'), (3, '运动户外'), (4, '美妆护肤'), (5, '女装')], verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.SmallIntegerField(choices=[(1, '普通会员'), (2, '白银会员'), (3, '黄金会员'), (4, '砖石会员')], verbose_name='用户的会员等级'),
        ),
        migrations.AddField(
            model_name='order',
            name='oredr_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applet.order_detail', verbose_name='订单外键'),
        ),
    ]
