# Generated by Django 2.2.2 on 2021-10-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0002_auto_20211014_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subject',
            field=models.CharField(max_length=150, null=True, verbose_name='订单标题'),
        ),
    ]
