# Generated by Django 2.2.2 on 2021-10-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0003_order_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subject',
            new_name='order_title',
        ),
    ]
