# Generated by Django 2.2.2 on 2021-10-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0004_auto_20211014_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=32, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '已签收'), (5, '待评价'), (6, '已评价')], default=1, verbose_name='订单状态'),
        ),
    ]
