# Generated by Django 2.2.2 on 2021-10-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0005_auto_20211014_1946'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='order',
        #     name='trade_no',
        # ),
        migrations.AddField(
            model_name='order_detail',
            name='trade_no',
            field=models.CharField(max_length=64, null=True, verbose_name='流水号'),
        ),
    ]
