# Generated by Django 2.2.2 on 2021-10-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0008_remove_order_detail_trade_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=64, verbose_name='订单ID'),
        ),
    ]
