# Generated by Django 2.2.2 on 2021-10-14 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0009_auto_20211014_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productgoods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applet.productgoods', verbose_name='关联商品id'),
        ),
    ]
