# Generated by Django 2.2.2 on 2021-10-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0010_auto_20211014_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='goodcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productgood_num', models.CharField(max_length=10, verbose_name='该商品被添加到购物车的数量')),
                ('goodtocart_time', models.DateTimeField(auto_now_add=True, verbose_name='商品被添加的时间')),
                ('productgood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goodcart', to='applet.productgoods', verbose_name='关联商品id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applet.user', verbose_name='关联用户')),
            ],
        ),
    ]
