# Generated by Django 2.2.2 on 2021-10-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0011_goodcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '用户地址列表', 'verbose_name_plural': '用户地址列表'},
        ),
        migrations.AlterModelOptions(
            name='good_categorychild',
            options={'verbose_name': '商品子分类表', 'verbose_name_plural': '商品子分类表'},
        ),
        migrations.AlterModelOptions(
            name='goodcart',
            options={'verbose_name': '用户购物车列表', 'verbose_name_plural': '用户购物车列表'},
        ),
        migrations.AlterModelOptions(
            name='navar',
            options={'verbose_name': '首页导航列表', 'verbose_name_plural': '首页导航列表'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '商品订单信息列表', 'verbose_name_plural': '商品订单信息列表'},
        ),
        migrations.AlterModelOptions(
            name='order_detail',
            options={'verbose_name': '订单详情列表', 'verbose_name_plural': '订单详情列表'},
        ),
        migrations.AlterModelOptions(
            name='productgoods',
            options={'verbose_name': '商品列表', 'verbose_name_plural': '商品列表'},
        ),
        migrations.AlterModelOptions(
            name='productgoodsdetail',
            options={'verbose_name': '商品详情信息列表', 'verbose_name_plural': '商品详情信息列表'},
        ),
        migrations.AlterModelOptions(
            name='productgoodsdetail_img',
            options={'verbose_name': '商品详情图片列表', 'verbose_name_plural': '商品详情图片列表'},
        ),
        migrations.AlterModelOptions(
            name='productgoodsdetail_slideshow',
            options={'verbose_name': '商品详情页轮播图片列表', 'verbose_name_plural': '商品详情页轮播图片列表'},
        ),
        migrations.AlterModelOptions(
            name='productsale',
            options={'verbose_name': '新品特卖列表', 'verbose_name_plural': '新品特卖列表'},
        ),
        migrations.AlterModelOptions(
            name='slideshow',
            options={'verbose_name': '首页轮播图列表', 'verbose_name_plural': '首页轮播图列表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '小程序端用户列表', 'verbose_name_plural': '小程序端用户列表'},
        ),
        migrations.AlterField(
            model_name='good_categorychild',
            name='category',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applet.good_category', verbose_name='主分类id'),
        ),
        migrations.AlterField(
            model_name='good_categorychild',
            name='name',
            field=models.CharField(max_length=16, verbose_name='商品子分类名称'),
        ),
        migrations.AlterField(
            model_name='goodcart',
            name='goodtocart_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加的时间'),
        ),
        migrations.AlterField(
            model_name='goodcart',
            name='productgood_num',
            field=models.CharField(max_length=10, verbose_name='添加到购物车的商品数量'),
        ),
        migrations.AlterField(
            model_name='goodcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applet.user', verbose_name='关联用户id'),
        ),
        migrations.AlterField(
            model_name='navar',
            name='navar_name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='navar',
            name='seq',
            field=models.IntegerField(verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='订单在用户层面是否删除', verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_addr',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='applet.address', verbose_name='关联地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_finishtime',
            field=models.DateTimeField(null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=64, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_paytime',
            field=models.DateTimeField(null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_title',
            field=models.CharField(max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_price',
            field=models.FloatField(verbose_name='支付金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_no',
            field=models.CharField(max_length=64, null=True, verbose_name='支付宝流水号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=True, to='applet.user', verbose_name='关联用户id'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='logistics_company',
            field=models.SmallIntegerField(choices=[(1, '京东'), (2, '顺丰'), (3, '圆通'), (4, '申通'), (5, '百世')], verbose_name='物流公司'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='categorychild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applet.good_categorychild', verbose_name='所属子分类'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='applet.productgoodsdetail', verbose_name='详情信息'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='goods_type',
            field=models.SmallIntegerField(choices=[(1, '电脑办公'), (2, '手机'), (3, '运动户外'), (4, '美妆护肤'), (5, '女装')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='is_putaway',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='price',
            field=models.FloatField(verbose_name='现价格'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='privilegePrice',
            field=models.FloatField(verbose_name='原价格'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='show_img',
            field=models.CharField(max_length=256, verbose_name='展示图片路径'),
        ),
        migrations.AlterField(
            model_name='productgoods',
            name='show_video',
            field=models.CharField(max_length=256, verbose_name='有关视频'),
        ),
        migrations.AlterField(
            model_name='productgoodsdetail',
            name='characteristic',
            field=models.CharField(max_length=128, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='productgoodsdetail',
            name='title',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='productgoodsdetail_img',
            name='detail_img',
            field=models.CharField(max_length=256, verbose_name='详情页商品详情图片'),
        ),
        migrations.AlterField(
            model_name='productgoodsdetail_slideshow',
            name='detail_slideshow',
            field=models.CharField(max_length=256, verbose_name='详情页轮播图'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='remark',
            field=models.CharField(max_length=64, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='banner_name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='click_url',
            field=models.CharField(max_length=256, verbose_name='点击链接'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='img_url',
            field=models.TextField(verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=64, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=64, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='user',
            name='headingurl',
            field=models.TextField(verbose_name='头像地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(max_length=32, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(max_length=64, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(help_text='值为1时是男性，为2时是女性，0是未知', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_balance',
            field=models.FloatField(default=0, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_isactive',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.SmallIntegerField(choices=[(1, '普通会员'), (2, '白银会员'), (3, '黄金会员'), (4, '砖石会员')], verbose_name='会员等级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_openid',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_point',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, verbose_name='昵称'),
        ),
    ]
