# Generated by Django 2.2.2 on 2021-10-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0012_auto_20211019_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='logistics_company',
            field=models.SmallIntegerField(choices=[(1, '京东'), (2, '顺丰'), (3, '圆通'), (4, '申通'), (5, '百世')], null=True, verbose_name='物流公司'),
        ),
    ]
