# Generated by Django 2.2.2 on 2021-10-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0013_auto_20211019_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good_category',
            options={'verbose_name': '分类表', 'verbose_name_plural': '分类表'},
        ),
        migrations.AlterModelOptions(
            name='good_categorychild',
            options={'verbose_name': '子分类表', 'verbose_name_plural': '子分类表'},
        ),
        migrations.AlterModelOptions(
            name='productgoodsdetail',
            options={'verbose_name': '商品详情列表', 'verbose_name_plural': '商品详情列表'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=256, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=16, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='address',
            name='transportDay',
            field=models.CharField(default='', max_length=64, verbose_name='收货时间'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=True, to='applet.user', verbose_name='关联用户'),
        ),
    ]
